### ISSUE TITLE
Non consistence style 

### ISSUE THREAD

**Issue by Luchanso** [qqLyamin/k_means_remaster#2]
https://github.com/qqLyamin/k_means_remaster/blob/6dab50f1e3befba82f71b359fa1e728d7e3d43be/klasters/kmeans.cpp#L17
https://github.com/qqLyamin/k_means_remaster/blob/6dab50f1e3befba82f71b359fa1e728d7e3d43be/klasters/kmeans.cpp#L26

**Comment by qqLyamin** [comment]
fixed
